package com.ipn.mx.model.entities;
// Generated 28/03/2017 01:03:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Coordinador generated by hbm2java
 */
@Entity
@Table(name="coordinador"
    ,catalog="torneofutbol"
)
public class Coordinador  implements java.io.Serializable {


     private String usuario;
     private String contrasenia;
     private Set torneos = new HashSet(0);

    public Coordinador() {
    }

	
    public Coordinador(String usuario) {
        this.usuario = usuario;
    }
    public Coordinador(String usuario, String contrasenia, Set torneos) {
       this.usuario = usuario;
       this.contrasenia = contrasenia;
       this.torneos = torneos;
    }
   
     @Id 

    
    @Column(name="usuario", unique=true, nullable=false, length=30)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="contrasenia", length=30)
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="coordinador")
    public Set getTorneos() {
        return this.torneos;
    }
    
    public void setTorneos(Set torneos) {
        this.torneos = torneos;
    }




}


