package com.ipn.mx.model.entities;
// Generated 28/03/2017 01:03:57 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EventoId generated by hbm2java
 */
@Embeddable
public class EventoId  implements java.io.Serializable {


     private int idEvento;
     private int torneoIdTorneo;

    public EventoId() {
    }

    public EventoId(int idEvento, int torneoIdTorneo) {
       this.idEvento = idEvento;
       this.torneoIdTorneo = torneoIdTorneo;
    }
   


    @Column(name="id_Evento", nullable=false)
    public int getIdEvento() {
        return this.idEvento;
    }
    
    public void setIdEvento(int idEvento) {
        this.idEvento = idEvento;
    }


    @Column(name="Torneo_id_Torneo", nullable=false)
    public int getTorneoIdTorneo() {
        return this.torneoIdTorneo;
    }
    
    public void setTorneoIdTorneo(int torneoIdTorneo) {
        this.torneoIdTorneo = torneoIdTorneo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EventoId) ) return false;
		 EventoId castOther = ( EventoId ) other; 
         
		 return (this.getIdEvento()==castOther.getIdEvento())
 && (this.getTorneoIdTorneo()==castOther.getTorneoIdTorneo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEvento();
         result = 37 * result + this.getTorneoIdTorneo();
         return result;
   }   


}


