package com.ipn.mx.model.entities;
// Generated 28/03/2017 01:03:57 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * JugadorId generated by hbm2java
 */
@Embeddable
public class JugadorId  implements java.io.Serializable {


     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String correo;

    public JugadorId() {
    }

    public JugadorId(String nombre, String apellidoPaterno, String apellidoMaterno, String correo) {
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.correo = correo;
    }
   


    @Column(name="nombre", nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }


    @Column(name="apellidoPaterno", nullable=false, length=30)
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }


    @Column(name="apellidoMaterno", nullable=false, length=30)
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }


    @Column(name="correo", nullable=false, length=30)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JugadorId) ) return false;
		 JugadorId castOther = ( JugadorId ) other; 
         
		 return ( (this.getNombre()==castOther.getNombre()) || ( this.getNombre()!=null && castOther.getNombre()!=null && this.getNombre().equals(castOther.getNombre()) ) )
 && ( (this.getApellidoPaterno()==castOther.getApellidoPaterno()) || ( this.getApellidoPaterno()!=null && castOther.getApellidoPaterno()!=null && this.getApellidoPaterno().equals(castOther.getApellidoPaterno()) ) )
 && ( (this.getApellidoMaterno()==castOther.getApellidoMaterno()) || ( this.getApellidoMaterno()!=null && castOther.getApellidoMaterno()!=null && this.getApellidoMaterno().equals(castOther.getApellidoMaterno()) ) )
 && ( (this.getCorreo()==castOther.getCorreo()) || ( this.getCorreo()!=null && castOther.getCorreo()!=null && this.getCorreo().equals(castOther.getCorreo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNombre() == null ? 0 : this.getNombre().hashCode() );
         result = 37 * result + ( getApellidoPaterno() == null ? 0 : this.getApellidoPaterno().hashCode() );
         result = 37 * result + ( getApellidoMaterno() == null ? 0 : this.getApellidoMaterno().hashCode() );
         result = 37 * result + ( getCorreo() == null ? 0 : this.getCorreo().hashCode() );
         return result;
   }   


}


