package com.ipn.mx.model.entities;
// Generated 28/03/2017 01:03:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PartidoId generated by hbm2java
 */
@Embeddable
public class PartidoId  implements java.io.Serializable {


     private Date horario;
     private int eventoIdEvento;
     private int eventoTorneoIdTorneo;

    public PartidoId() {
    }

    public PartidoId(Date horario, int eventoIdEvento, int eventoTorneoIdTorneo) {
       this.horario = horario;
       this.eventoIdEvento = eventoIdEvento;
       this.eventoTorneoIdTorneo = eventoTorneoIdTorneo;
    }
   


    @Column(name="horario", nullable=false, length=19)
    public Date getHorario() {
        return this.horario;
    }
    
    public void setHorario(Date horario) {
        this.horario = horario;
    }


    @Column(name="Evento_id_Evento", nullable=false)
    public int getEventoIdEvento() {
        return this.eventoIdEvento;
    }
    
    public void setEventoIdEvento(int eventoIdEvento) {
        this.eventoIdEvento = eventoIdEvento;
    }


    @Column(name="Evento_Torneo_id_Torneo", nullable=false)
    public int getEventoTorneoIdTorneo() {
        return this.eventoTorneoIdTorneo;
    }
    
    public void setEventoTorneoIdTorneo(int eventoTorneoIdTorneo) {
        this.eventoTorneoIdTorneo = eventoTorneoIdTorneo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PartidoId) ) return false;
		 PartidoId castOther = ( PartidoId ) other; 
         
		 return ( (this.getHorario()==castOther.getHorario()) || ( this.getHorario()!=null && castOther.getHorario()!=null && this.getHorario().equals(castOther.getHorario()) ) )
 && (this.getEventoIdEvento()==castOther.getEventoIdEvento())
 && (this.getEventoTorneoIdTorneo()==castOther.getEventoTorneoIdTorneo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getHorario() == null ? 0 : this.getHorario().hashCode() );
         result = 37 * result + this.getEventoIdEvento();
         result = 37 * result + this.getEventoTorneoIdTorneo();
         return result;
   }   


}


