package com.ipn.mx.model.entities;
// Generated 28/03/2017 01:03:57 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PartidoEquipoId generated by hbm2java
 */
@Embeddable
public class PartidoEquipoId  implements java.io.Serializable {


     private Date partidoHorario;
     private int partidoEventoIdEvento;
     private int partidoEventoTorneoIdTorneo;
     private String equipoNombre;

    public PartidoEquipoId() {
    }

    public PartidoEquipoId(Date partidoHorario, int partidoEventoIdEvento, int partidoEventoTorneoIdTorneo, String equipoNombre) {
       this.partidoHorario = partidoHorario;
       this.partidoEventoIdEvento = partidoEventoIdEvento;
       this.partidoEventoTorneoIdTorneo = partidoEventoTorneoIdTorneo;
       this.equipoNombre = equipoNombre;
    }
   


    @Column(name="Partido_horario", nullable=false, length=19)
    public Date getPartidoHorario() {
        return this.partidoHorario;
    }
    
    public void setPartidoHorario(Date partidoHorario) {
        this.partidoHorario = partidoHorario;
    }


    @Column(name="Partido_Evento_id_Evento", nullable=false)
    public int getPartidoEventoIdEvento() {
        return this.partidoEventoIdEvento;
    }
    
    public void setPartidoEventoIdEvento(int partidoEventoIdEvento) {
        this.partidoEventoIdEvento = partidoEventoIdEvento;
    }


    @Column(name="Partido_Evento_Torneo_id_Torneo", nullable=false)
    public int getPartidoEventoTorneoIdTorneo() {
        return this.partidoEventoTorneoIdTorneo;
    }
    
    public void setPartidoEventoTorneoIdTorneo(int partidoEventoTorneoIdTorneo) {
        this.partidoEventoTorneoIdTorneo = partidoEventoTorneoIdTorneo;
    }


    @Column(name="Equipo_nombre", nullable=false, length=50)
    public String getEquipoNombre() {
        return this.equipoNombre;
    }
    
    public void setEquipoNombre(String equipoNombre) {
        this.equipoNombre = equipoNombre;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PartidoEquipoId) ) return false;
		 PartidoEquipoId castOther = ( PartidoEquipoId ) other; 
         
		 return ( (this.getPartidoHorario()==castOther.getPartidoHorario()) || ( this.getPartidoHorario()!=null && castOther.getPartidoHorario()!=null && this.getPartidoHorario().equals(castOther.getPartidoHorario()) ) )
 && (this.getPartidoEventoIdEvento()==castOther.getPartidoEventoIdEvento())
 && (this.getPartidoEventoTorneoIdTorneo()==castOther.getPartidoEventoTorneoIdTorneo())
 && ( (this.getEquipoNombre()==castOther.getEquipoNombre()) || ( this.getEquipoNombre()!=null && castOther.getEquipoNombre()!=null && this.getEquipoNombre().equals(castOther.getEquipoNombre()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPartidoHorario() == null ? 0 : this.getPartidoHorario().hashCode() );
         result = 37 * result + this.getPartidoEventoIdEvento();
         result = 37 * result + this.getPartidoEventoTorneoIdTorneo();
         result = 37 * result + ( getEquipoNombre() == null ? 0 : this.getEquipoNombre().hashCode() );
         return result;
   }   


}


