package com.ipn.mx.model.entities;
// Generated 28/03/2017 01:03:57 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PartidoEquipo generated by hbm2java
 */
@Entity
@Table(name="partido_equipo"
    ,catalog="torneofutbol"
)
public class PartidoEquipo  implements java.io.Serializable {


     private PartidoEquipoId id;
     private Equipo equipo;
     private Partido partido;
     private Integer goles;
     private Integer golesPenales;

    public PartidoEquipo() {
    }
    
    public PartidoEquipo(PartidoEquipoId id, Equipo equipo, Partido partido) {
        this.id = id;
        this.equipo = equipo;
        this.partido = partido;
    }
    public PartidoEquipo(PartidoEquipoId id, Equipo equipo, Partido partido, Integer goles, Integer golesPenales) {
       this.id = id;
       this.equipo = equipo;
       this.partido = partido;
       this.goles = goles;
       this.golesPenales = golesPenales;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="partidoHorario", column=@Column(name="Partido_horario", nullable=false, length=19) ), 
        @AttributeOverride(name="partidoEventoIdEvento", column=@Column(name="Partido_Evento_id_Evento", nullable=false) ), 
        @AttributeOverride(name="partidoEventoTorneoIdTorneo", column=@Column(name="Partido_Evento_Torneo_id_Torneo", nullable=false) ), 
        @AttributeOverride(name="equipoNombre", column=@Column(name="Equipo_nombre", nullable=false, length=50) ) } )
    public PartidoEquipoId getId() {
        return this.id;
    }
    
    public void setId(PartidoEquipoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Equipo_nombre", nullable=false, insertable=false, updatable=false)
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="Partido_horario", referencedColumnName="horario", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="Partido_Evento_id_Evento", referencedColumnName="Evento_id_Evento", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="Partido_Evento_Torneo_id_Torneo", referencedColumnName="Evento_Torneo_id_Torneo", nullable=false, insertable=false, updatable=false) } )
    public Partido getPartido() {
        return this.partido;
    }
    
    public void setPartido(Partido partido) {
        this.partido = partido;
    }

    
    @Column(name="goles")
    public Integer getGoles() {
        return this.goles;
    }
    
    public void setGoles(Integer goles) {
        this.goles = goles;
    }

    
    @Column(name="golesPenales")
    public Integer getGolesPenales() {
        return this.golesPenales;
    }
    
    public void setGolesPenales(Integer golesPenales) {
        this.golesPenales = golesPenales;
    }




}