package com.ipn.mx.model.entities;
// Generated 28/03/2017 01:03:57 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

/**
 * Representante generated by hbm2java
 */
@Entity
@Table(name="Representante"
    ,catalog="TorneoFutbol"
)
public class Representante  implements java.io.Serializable {


     private RepresentanteId id;
     private Jugador jugador;
     private String contrasenia;
     private String telefono;

    public Representante() {
    }

    public Representante(Jugador jugador, String contrasenia, String telefono) {
       this.jugador = jugador;
       this.contrasenia = contrasenia;
       this.telefono = telefono;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="jugadorNombre", column=@Column(name="jugador_nombre", nullable=false, length=30) ), 
        @AttributeOverride(name="jugadorApellidoPaterno", column=@Column(name="jugador_apellidoPaterno", nullable=false, length=30) ), 
        @AttributeOverride(name="jugadorApellidoMaterno", column=@Column(name="jugador_apellidoMaterno", nullable=false, length=30) ), 
        @AttributeOverride(name="jugadorCorreo", column=@Column(name="jugador_correo", nullable=false, length=30) ) } )
    public RepresentanteId getId() {
        return this.id;
    }
    
    public void setId(RepresentanteId id) {
        this.id = id;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Jugador getJugador() {
        return this.jugador;
    }
    
    public void setJugador(Jugador jugador) {
        this.jugador = jugador;
    }

    
    @Column(name="contrasenia", nullable=false, length=30)
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

    
    @Column(name="telefono", nullable=false, length=30)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


