package com.ipn.mx.model.entities;
// Generated 28/03/2017 01:03:57 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RepresentanteId generated by hbm2java
 */
@Embeddable
public class RepresentanteId  implements java.io.Serializable {


     private String jugadorNombre;
     private String jugadorApellidoPaterno;
     private String jugadorApellidoMaterno;
     private String jugadorCorreo;

    public RepresentanteId() {
    }

    public RepresentanteId(String jugadorNombre, String jugadorApellidoPaterno, String jugadorApellidoMaterno, String jugadorCorreo) {
       this.jugadorNombre = jugadorNombre;
       this.jugadorApellidoPaterno = jugadorApellidoPaterno;
       this.jugadorApellidoMaterno = jugadorApellidoMaterno;
       this.jugadorCorreo = jugadorCorreo;
    }
   


    @Column(name="jugador_nombre", nullable=false, length=30)
    public String getJugadorNombre() {
        return this.jugadorNombre;
    }
    
    public void setJugadorNombre(String jugadorNombre) {
        this.jugadorNombre = jugadorNombre;
    }


    @Column(name="jugador_apellidoPaterno", nullable=false, length=30)
    public String getJugadorApellidoPaterno() {
        return this.jugadorApellidoPaterno;
    }
    
    public void setJugadorApellidoPaterno(String jugadorApellidoPaterno) {
        this.jugadorApellidoPaterno = jugadorApellidoPaterno;
    }


    @Column(name="jugador_apellidoMaterno", nullable=false, length=30)
    public String getJugadorApellidoMaterno() {
        return this.jugadorApellidoMaterno;
    }
    
    public void setJugadorApellidoMaterno(String jugadorApellidoMaterno) {
        this.jugadorApellidoMaterno = jugadorApellidoMaterno;
    }


    @Column(name="jugador_correo", nullable=false, length=30)
    public String getJugadorCorreo() {
        return this.jugadorCorreo;
    }
    
    public void setJugadorCorreo(String jugadorCorreo) {
        this.jugadorCorreo = jugadorCorreo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RepresentanteId) ) return false;
		 RepresentanteId castOther = ( RepresentanteId ) other; 
         
		 return ( (this.getJugadorNombre()==castOther.getJugadorNombre()) || ( this.getJugadorNombre()!=null && castOther.getJugadorNombre()!=null && this.getJugadorNombre().equals(castOther.getJugadorNombre()) ) )
 && ( (this.getJugadorApellidoPaterno()==castOther.getJugadorApellidoPaterno()) || ( this.getJugadorApellidoPaterno()!=null && castOther.getJugadorApellidoPaterno()!=null && this.getJugadorApellidoPaterno().equals(castOther.getJugadorApellidoPaterno()) ) )
 && ( (this.getJugadorApellidoMaterno()==castOther.getJugadorApellidoMaterno()) || ( this.getJugadorApellidoMaterno()!=null && castOther.getJugadorApellidoMaterno()!=null && this.getJugadorApellidoMaterno().equals(castOther.getJugadorApellidoMaterno()) ) )
 && ( (this.getJugadorCorreo()==castOther.getJugadorCorreo()) || ( this.getJugadorCorreo()!=null && castOther.getJugadorCorreo()!=null && this.getJugadorCorreo().equals(castOther.getJugadorCorreo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getJugadorNombre() == null ? 0 : this.getJugadorNombre().hashCode() );
         result = 37 * result + ( getJugadorApellidoPaterno() == null ? 0 : this.getJugadorApellidoPaterno().hashCode() );
         result = 37 * result + ( getJugadorApellidoMaterno() == null ? 0 : this.getJugadorApellidoMaterno().hashCode() );
         result = 37 * result + ( getJugadorCorreo() == null ? 0 : this.getJugadorCorreo().hashCode() );
         return result;
   }   


}


