package com.ipn.mx.model.entities;
// Generated 28/03/2017 01:03:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Torneo generated by hbm2java
 */
@Entity
@Table(name="torneo"
    ,catalog="torneofutbol"
)
public class Torneo  implements java.io.Serializable {


     private int idTorneo;
     private Coordinador coordinador;
     private String nombre;
     private String tipoTorneo;
     private Set<Equipo> equipos = new HashSet<Equipo>(0);
     private Set<Evento> eventos = new HashSet<Evento>(0);

    public Torneo() {
    }

	
    public Torneo(int idTorneo, Coordinador coordinador, String nombre, String tipoTorneo) {
        this.idTorneo = idTorneo;
        this.coordinador = coordinador;
        this.nombre = nombre;
        this.tipoTorneo = tipoTorneo;
    }
    public Torneo(int idTorneo, Coordinador coordinador, String nombre, String tipoTorneo, Set<Equipo> equipos, Set<Evento> eventos) {
       this.idTorneo = idTorneo;
       this.coordinador = coordinador;
       this.nombre = nombre;
       this.tipoTorneo = tipoTorneo;
       this.equipos = equipos;
       this.eventos = eventos;
    }
   
     @Id 

    
    @Column(name="id_Torneo", unique=true, nullable=false)
    public int getIdTorneo() {
        return this.idTorneo;
    }
    
    public void setIdTorneo(int idTorneo) {
        this.idTorneo = idTorneo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Coordinador_usuario", nullable=false)
    public Coordinador getCoordinador() {
        return this.coordinador;
    }
    
    public void setCoordinador(Coordinador coordinador) {
        this.coordinador = coordinador;
    }

    
    @Column(name="nombre", nullable=false, length=10)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="tipoTorneo", nullable=false, length=11)
    public String getTipoTorneo() {
        return this.tipoTorneo;
    }
    
    public void setTipoTorneo(String tipoTorneo) {
        this.tipoTorneo = tipoTorneo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="torneo")
    public Set<Equipo> getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Set<Equipo> equipos) {
        this.equipos = equipos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="torneo")
    public Set<Evento> getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set<Evento> eventos) {
        this.eventos = eventos;
    }




}


